-- DropForeignKey
ALTER TABLE "MVA" DROP CONSTRAINT "MVA_nbmSTId_fkey";

-- AddForeignKey
ALTER TABLE "MVA" ADD CONSTRAINT "MVA_nbmSTId_fkey" FOREIGN KEY ("nbmSTId") REFERENCES "nbms_st"("id") ON DELETE CASCADE ON UPDATE CASCADE;
